### ISSUE TITLE
Issue pipeline "Freesurfer outputs to Brainvisa conversion pipeline"

### ISSUE THREAD

**Issue by c-langlet** [brainvisa/brainvisa_freesurfer#1]
Hello, 

I encountered a bug in the process "Convert Freesurfer images to nifti format".

**Error:**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/casa/host/build/python/freesurfer/setAnatTransformation.py", line 18, in setAnatTransformation
    vs2 = (s2m.transform(v) - s2m.transform([0, 0, 0])) / 2.
TypeError: unsupported operand type(s) for -: 'vector_DOUBLE' and 'vector_S32

**Fix:**
This seems to work but not sure if its valid. In _/casa/host/build/python/freesurfer/setAnatTransformation.py_, I used numpy bindings:
vs2 = (s2m.transform(v).np - s2m.transform([0, 0, 0]).np) / 2.

**Comment by denisri** [comment]
You're right, the Transformation behaviour has changed in aims 5.2 (current master branches): as it has been extended to more than 3D, the former API using aims.Point3df (and returning the same) has been overloaded to work on arbitrary size vectors, that is `std::vector` in C++, or `list`s in python. The return type for these types of inputs are thus also lists, and lists cannot be added like points or numpy arrays. This explains the problem.
Your solution should be OK, the only difference is that now `vs2` is a numpy array, not an `aims.Point3df` as it used to be, but auto conversions should behave correctly after that.
You can push your fix, thanks.
